name: Build Windows
on:
  push:
    branches: [ master, actions ]
  pull_request:
    branches: [ master, actions ]

jobs:
  build:
    name: Build - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-latest
            name: "Windows x64 MSVC"
            artifact: "Windows-MSVC.tar.xz"
            build_type: "RelWithDebInfo"
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
            cc: "cl"
            cxx: "cl"
            archiver: "7z a"
            generators: "Visual Studio 16 2019"
            build_dir: 'build'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          path: 'pragma_udm_wrapper'

      - name: Setup
        id: setup
        uses: Silverlan/common_actions/setup@main
          
      - name: Download binaries
        uses: Silverlan/common_actions/download_build_binaries@main
        continue-on-error: true
          
      - name: Build
        id: build
        uses: Silverlan/pragma_udm_wrapper/github_actions/build@actions
        with:
          root_dir: "${{ env.GA_ROOT_DIR }}"
          should_checkout: "0"
          dir: '.'
          
      - name: Upload binaries
        uses: Silverlan/common_actions/upload_build_binaries@main
        
      - name: Prepare release package
        shell: bash
        run: |
          # remove unwanted files
          rm -rf ./pragma_udm_wrapper/tests
          rm -rf ./pragma_udm_wrapper/.github
          rm -rf ./pragma_udm_wrapper/github_actions
          rm -rf ./pragma_udm_wrapper/README.MD
          rm -rf ./pragma_udm_wrapper/.gitignore
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: pragma_udm_wrapper
          retention-days: 30
          path: |
            ./pragma_udm_wrapper*
